// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"encoding/json"
	"time"
)

type Order struct {
	ID          int64           `db:"id"`
	UserID      int64           `db:"user_id"`
	TotalAmount string          `db:"total_amount"`
	Status      string          `db:"status"`
	Items       json.RawMessage `db:"items"`
	CreatedAt   time.Time       `db:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at"`
}

type User struct {
	ID           int64     `db:"id"`
	Email        string    `db:"email"`
	PasswordHash string    `db:"password_hash"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}
