// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (user_id, total_amount, status, items, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateOrderParams struct {
	UserID      int64           `db:"user_id"`
	TotalAmount string          `db:"total_amount"`
	Status      string          `db:"status"`
	Items       json.RawMessage `db:"items"`
	CreatedAt   time.Time       `db:"created_at"`
	UpdatedAt   time.Time       `db:"updated_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder,
		arg.UserID,
		arg.TotalAmount,
		arg.Status,
		arg.Items,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const deleteOrder = `-- name: DeleteOrder :execresult
DELETE FROM orders
WHERE id = ?
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteOrder, id)
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, total_amount, status, items, created_at, updated_at
FROM orders
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (*Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, user_id, total_amount, status, items, created_at, updated_at
FROM orders
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersByUserID(ctx context.Context, userID int64) ([]*Order, error) {
	rows, err := q.db.QueryContext(ctx, getOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.Items,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :execresult
UPDATE orders
SET user_id = ?, total_amount = ?, status = ?, items = ?, updated_at = ?
WHERE id = ?
`

type UpdateOrderParams struct {
	UserID      int64           `db:"user_id"`
	TotalAmount string          `db:"total_amount"`
	Status      string          `db:"status"`
	Items       json.RawMessage `db:"items"`
	UpdatedAt   time.Time       `db:"updated_at"`
	ID          int64           `db:"id"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateOrder,
		arg.UserID,
		arg.TotalAmount,
		arg.Status,
		arg.Items,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateOrderStatus = `-- name: UpdateOrderStatus :execresult
UPDATE orders
SET status = ?, updated_at = ?
WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status    string    `db:"status"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        int64     `db:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.UpdatedAt, arg.ID)
}
