// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
	"go-clean-arch/internal/adapter/gateway"
	"go-clean-arch/internal/adapter/repository"
	"go-clean-arch/internal/delivery/consumer"
	"go-clean-arch/internal/delivery/http"
	"go-clean-arch/internal/delivery/http/handler"
	"go-clean-arch/internal/delivery/job"
	"go-clean-arch/internal/usecase"
	"go-clean-arch/pkg/config"
)

// Injectors from wire.go:

// InitializeAPIRouter initializes the API router with all dependencies
func InitializeAPIRouter(db *sqlx.DB, cfg *config.Config) *gin.Engine {
	userRepository := repository.NewUserRepository(db)
	userInteractor := usecase.NewUserInteractor(userRepository)
	userHandler := handler.NewUserHandler(userInteractor)
	orderRepository := repository.NewOrderRepository(db)
	string2 := ProvideStripeAPIKey(cfg)
	paymentGateway := gateway.NewStripeGateway(string2)
	orderInteractor := usecase.NewOrderInteractor(orderRepository, userRepository, paymentGateway)
	orderHandler := handler.NewOrderHandler(orderInteractor)
	healthHandler := handler.NewHealthHandler(db)
	engine := http.Router(userHandler, orderHandler, healthHandler)
	return engine
}

// InitializeWorker initializes the worker with all dependencies
func InitializeWorker(db *sqlx.DB, cfg *config.Config) *consumer.OrderConsumer {
	orderRepository := repository.NewOrderRepository(db)
	userRepository := repository.NewUserRepository(db)
	string2 := ProvideStripeAPIKey(cfg)
	paymentGateway := gateway.NewStripeGateway(string2)
	orderInteractor := usecase.NewOrderInteractor(orderRepository, userRepository, paymentGateway)
	orderConsumer := consumer.NewOrderConsumer(orderInteractor)
	return orderConsumer
}

// InitializeCronScheduler initializes the cron scheduler with all dependencies
func InitializeCronScheduler(db *sqlx.DB, cfg *config.Config) *job.Scheduler {
	userRepository := repository.NewUserRepository(db)
	userInteractor := usecase.NewUserInteractor(userRepository)
	orderRepository := repository.NewOrderRepository(db)
	string2 := ProvideStripeAPIKey(cfg)
	paymentGateway := gateway.NewStripeGateway(string2)
	orderInteractor := usecase.NewOrderInteractor(orderRepository, userRepository, paymentGateway)
	dailyReportJob := job.NewDailyReportJob(userInteractor, orderInteractor)
	scheduler := job.NewScheduler(dailyReportJob)
	return scheduler
}

// wire.go:

// ProvideStripeAPIKey provides the Stripe API key from config
func ProvideStripeAPIKey(cfg *config.Config) string {
	return cfg.Stripe.APIKey
}

// RepositorySet provides all repository dependencies
var RepositorySet = wire.NewSet(repository.NewUserRepository, repository.NewOrderRepository)

// GatewaySet provides all gateway dependencies
var GatewaySet = wire.NewSet(
	ProvideStripeAPIKey, gateway.NewStripeGateway,
)

// UseCaseSet provides all use case dependencies
var UseCaseSet = wire.NewSet(usecase.NewUserInteractor, usecase.NewOrderInteractor, wire.Bind(new(usecase.UserUsecase), new(*usecase.UserInteractor)), wire.Bind(new(usecase.OrderUsecase), new(*usecase.OrderInteractor)))

// HandlerSet provides all HTTP handler dependencies
var HandlerSet = wire.NewSet(handler.NewUserHandler, handler.NewOrderHandler, handler.NewHealthHandler)

// ConsumerSet provides all message consumer dependencies
var ConsumerSet = wire.NewSet(consumer.NewOrderConsumer)

// JobSet provides all job dependencies
var JobSet = wire.NewSet(job.NewDailyReportJob, job.NewScheduler)
